kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-fiber-order-api
spec:
  selector:
    matchLabels:
      app: go-fiber-order-api
  replicas: 1
  template:
    metadata:
      labels:
        app: go-fiber-order-api
    spec:
      containers:
        - name: go-fiber-order-api
          image: go-fiber-order-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
